# Here, in this Jupyter notebook, you will see the whole syntax of Numerical Python which is widely used in variety of field including Machine Learning, Statistical Programming, Data Engineering and Data Analysis.

In [141]:
#import numpy to use it
import numpy as np

In [142]:
#0 dimensional tensors -- scalars
arr1=np.array(1)

In [143]:
arr1

array(1)

In [144]:
arr2=np.array([1,2,3,4,5])

In [145]:
arr2

array([1, 2, 3, 4, 5])

In [146]:
arr3=np.array([[1,2,3],[4,5,6]])

In [147]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
arr4=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [149]:
arr5=np.zeros(5)

In [150]:
arr5

array([0., 0., 0., 0., 0.])

In [151]:
arr6=np.ones(5)

In [152]:
arr6

array([1., 1., 1., 1., 1.])

In [153]:
arr7= np.zeros((2,3))

In [154]:
arr7

array([[0., 0., 0.],
       [0., 0., 0.]])

In [155]:
arr8=np.identity(5)

In [156]:
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [157]:
arr9=np.full((3,3),7)

In [158]:
arr9

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [159]:
arr10=np.arange(0,11,1)

In [160]:
arr10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [161]:
arr10=np.arange(0,11)
arr10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
arr11=np.arange(10,0,-1)

In [163]:
arr11

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [164]:
arr12=np.arange(0,101,2)

In [165]:
arr12

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [166]:
arr13=np.linspace(5,10,10)

In [167]:
arr13

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [168]:
arr14=np.random.rand(2,3)

In [169]:
arr14

array([[0.14970221, 0.63794497, 0.92395711],
       [0.71209365, 0.63944452, 0.06285124]])

In [170]:
arr15=np.random.randint(0,10,(2,3))

In [171]:
arr15

array([[4, 2, 5],
       [9, 5, 0]], dtype=int32)

In [172]:
arr16=arr15.copy()
arr16

array([[4, 2, 5],
       [9, 5, 0]], dtype=int32)

In [173]:
arr16.shape

(2, 3)

In [174]:
arr4.ndim

3

In [175]:
arr4.shape

(3, 2, 3)

In [176]:
arr4.size

18

In [177]:
arr4.itemsize

8

In [178]:
arr15.itemsize

4

In [179]:
arr15.dtype

dtype('int32')

In [180]:
arr4.dtype

dtype('int64')

In [181]:
arr13

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [182]:
arr13.dtype

dtype('float64')

In [183]:
arr4.astype('float')

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

In [184]:
arr13.astype('int')

array([ 5,  5,  6,  6,  7,  7,  8,  8,  9, 10])

In [185]:
np_array=np.arange(0,100)
py_list=range(100)

In [186]:
import sys


In [187]:
sys.getsizeof(80)*len(py_list)

2800

In [188]:
np_array.itemsize*np_array.size

800

In [189]:
sys.getsizeof(80)

28

In [190]:
import time
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()
c=[x+y for x,y in zip(x,y)]
print(time.time()-start_time)


3.3433682918548584


In [191]:
a=np.arange(100000)
b=np.arange(100000,200000)
start_time=time.time()
sum=a+b
print(time.time()-start_time)

0.004418373107910156


In [192]:
arr=np.arange(24)

In [193]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [194]:
arr[2]

np.int64(2)

In [195]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [196]:
arr=arr.reshape(6,4)

In [197]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [198]:
arr[2]

array([ 8,  9, 10, 11])

In [199]:
arr[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [200]:
arr[2,3]

np.int64(11)

In [201]:
arr[:,2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [202]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [203]:
arr[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [204]:
arr[5:7,1:3]

array([[21, 22]])

In [205]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [206]:
arr[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [207]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [208]:
for i in arr:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [209]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [210]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [211]:
arr1

array([1, 2, 3, 4, 5])

In [212]:
arr2

array([ 6,  7,  8,  9, 10])

In [213]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [214]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [215]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [216]:
arr1//arr2

array([0, 0, 0, 0, 0])

In [217]:
arr1=np.arange(0,6).reshape(2,3)
arr2=np.arange(6,12).reshape(3,2)


In [218]:
arr1.dot(arr2)

array([[ 28,  31],
       [100, 112]])

In [219]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [220]:
arr1>3

array([[False, False, False],
       [False,  True,  True]])

In [221]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [222]:
arr1.sum()

np.int64(15)

In [223]:
arr1.min()

np.int64(0)

In [224]:
arr1.max()

np.int64(5)

In [225]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
arr5

array([0., 0., 0., 0., 0.])

In [227]:
arr6

array([1., 1., 1., 1., 1.])

In [228]:
arr8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [229]:
arr9

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [230]:
arr10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [231]:
arr11

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [232]:
arr12

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [233]:
arr12.sum(axis=0)

np.int64(2550)

In [234]:
arr14.sum(axis=1)

array([1.71160429, 1.41438941])

In [235]:
arr14.sum(axis=0)

array([0.86179586, 1.27738949, 0.98680835])

In [237]:
arr14.std()

np.float64(0.30939693396621887)

In [238]:
arr.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399])

In [239]:
np.median(arr)

np.float64(11.5)

In [240]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [241]:
np.sin(arr14)

array([[0.14914368, 0.59554585, 0.79799268],
       [0.65342009, 0.5967498 , 0.06280987]])

In [242]:
arr14.min(axis=0)

array([0.14970221, 0.63794497, 0.06285124])